<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.0.1
 */

declare(strict_types=1);

namespace TypeLang\Parser\Internal;

use TypeLang\Parser\Exception;
use TypeLang\Type;

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

/**
 * @template TResult of mixed = mixed
 *
 * @template-implements \Phplrt\Contracts\Parser\ParserInterface<TResult>
 */
abstract class CompiledExecutor implements \Phplrt\Contracts\Parser\ParserInterface
{
    /** @var int */
    public const T_WHITESPACE = 0;
    /** @var int */
    public const T_EQ = 1;
    /** @var int */
    public const T_NOT = 2;
    /** @var int */
    public const T_TRUE_LITERAL = 3;
    /** @var int */
    public const T_FALSE_LITERAL = 4;
    /** @var int */
    public const T_NULL_LITERAL = 5;
    /** @var int */
    public const T_NAME_WITH_SPACE = 6;
    /** @var int */
    public const T_NAME = 7;
    /** @var int */
    public const T_NS_DELIMITER = 8;
    /** @var int */
    public const T_OR = 9;
    /** @var int */
    public const T_COMMA = 10;
    /** @var int */
    public const T_DOUBLE_COLON = 11;
    /** @var int */
    public const T_COLON = 12;
    /** @var int */
    public const T_ANGLE_BRACKET_OPEN = 13;
    /** @var int */
    public const T_ANGLE_BRACKET_CLOSE = 14;
    /** @var int */
    public const T_QMARK = 15;
    /** @var int */
    public const T_BRACE_OPEN = 16;
    /** @var int */
    public const T_BRACE_CLOSE = 17;
    /** @var int */
    public const T_PARENTHESIS_OPEN = 18;
    /** @var int */
    public const T_PARENTHESIS_CLOSE = 19;
    /** @var int */
    public const T_SQUARE_BRACKET_OPEN = 20;
    /** @var int */
    public const T_SQUARE_BRACKET_CLOSE = 21;
    /** @var int */
    public const T_AMP = 22;
    /** @var int */
    public const T_ELLIPSIS = 23;
    /** @var int */
    public const T_ASSIGN = 24;
    /** @var int */
    public const T_ASTERISK = 25;
    /** @var int */
    public const T_THIS = 26;
    /** @var int */
    public const T_VARIABLE = 27;
    /** @var int */
    public const T_DQ_STRING_LITERAL = 28;
    /** @var int */
    public const T_SQ_STRING_LITERAL = 29;
    /** @var int */
    public const T_FLOAT_LITERAL = 30;
    /** @var int */
    public const T_BIN_INT_LITERAL = 31;
    /** @var int */
    public const T_OCT_INT_LITERAL = 32;
    /** @var int */
    public const T_HEX_INT_LITERAL = 33;
    /** @var int */
    public const T_DEC_INT_LITERAL = 34;
    /** @var int */
    public const T_COMMENT = 35;
    /** @var int */
    public const T_DOC_COMMENT = 36;

    /**
     * @var \Phplrt\Contracts\Parser\ParserInterface<TResult>
     */
    protected readonly \Phplrt\Contracts\Parser\ParserInterface $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:is(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:1))|(?:(?:not(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:2))|(?:(?:(?i:true)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:3))|(?:(?:(?i:false)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:4))|(?:(?:(?i:null)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:5))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+\\s++)(*MARK:6))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+)(*MARK:7))|(?:(?:\\\\)(*MARK:8))|(?:(?:\\|)(*MARK:9))|(?:(?:,)(*MARK:10))|(?:(?:::)(*MARK:11))|(?:(?::)(*MARK:12))|(?:(?:<)(*MARK:13))|(?:(?:>)(*MARK:14))|(?:(?:\\?)(*MARK:15))|(?:(?:\\{)(*MARK:16))|(?:(?:\\})(*MARK:17))|(?:(?:\\()(*MARK:18))|(?:(?:\\))(*MARK:19))|(?:(?:\\[)(*MARK:20))|(?:(?:\\])(*MARK:21))|(?:(?:&)(*MARK:22))|(?:(?:\\.\\.\\.)(*MARK:23))|(?:(?:=)(*MARK:24))|(?:(?:\\*)(*MARK:25))|(?:(?:\\$this(?!(?:[a-zA-Z0-9_\\x80-\\xff])))(*MARK:26))|(?:(?:\\$(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9_\\x80-\\xff])*+)(*MARK:27))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:28))|(?:(?:\'[^\'\\\\]*+(?:\\\\.[^\'\\\\]*+)*+\')(*MARK:29))|(?:(?:(?:[-+])?(?:(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+)\\.(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+))?|\\.(?:(?:[0-9])(?:_?(?:[0-9]))*+))(?:(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+)))?|(?:(?:[0-9])(?:_?(?:[0-9]))*+)(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+))))(*MARK:30))|(?:(?:(?:[-+])?0[bB](?:(?:[01])(?:_?(?:[01]))*+))(*MARK:31))|(?:(?:(?:[-+])?0(?:[oO](?:(?:[0-7])(?:_?(?:[0-7]))*+)|(?:_?(?:[0-7]))++))(*MARK:32))|(?:(?:(?:[-+])?0[xX](?:(?:[0-9a-fA-F])(?:_?(?:[0-9a-fA-F]))*+))(*MARK:33))|(?:(?:(?:[-+])?(?:(?:(?:[1-9])(?:_?(?:[0-9]))*+)|0))(*MARK:34))|(?:(?:(?:\\/\\/|\\#)[^\\r\\n]*+)(*MARK:35))|(?:(?:\\/\\*.*?\\*\\/)(*MARK:36))|(?:(?:[^\\s]++)(*MARK:37)))/Ssm',
            channels: [
                'Hidden',
                35 => 'Hidden',
                'Hidden',
                'Unknown',
            ],
            names: [
                'T_WHITESPACE',
                'T_EQ',
                'T_NOT',
                'T_TRUE_LITERAL',
                'T_FALSE_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_FLOAT_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Alternation([1, 155]),
                new \Phplrt\Parser\Grammar\Concatenation([2, 147]),
                new \Phplrt\Parser\Grammar\Concatenation([3, 143]),
                new \Phplrt\Parser\Grammar\Concatenation([4, 139]),
                new \Phplrt\Parser\Grammar\Alternation([5, 8]),
                new \Phplrt\Parser\Grammar\Concatenation([6, 7]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, false),
                new \Phplrt\Parser\Grammar\Concatenation([8]),
                new \Phplrt\Parser\Grammar\Concatenation([9, 134]),
                new \Phplrt\Parser\Grammar\Alternation([10, 13, 14, 28]),
                new \Phplrt\Parser\Grammar\Concatenation([11, 0, 12]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Alternation([15, 27]),
                new \Phplrt\Parser\Grammar\Alternation([16, 19, 20, 25, 26]),
                new \Phplrt\Parser\Grammar\Alternation([17, 18]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FLOAT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Alternation([21, 22, 23, 24]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BIN_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OCT_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_HEX_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DEC_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Concatenation([29, 57]),
                new \Phplrt\Parser\Grammar\Alternation([30, 55]),
                new \Phplrt\Parser\Grammar\Concatenation([31, 47]),
                new \Phplrt\Parser\Grammar\Alternation([32, 46]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 34, 43]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NS_DELIMITER, false),
                new \Phplrt\Parser\Grammar\Concatenation([35]),
                new \Phplrt\Parser\Grammar\Alternation([36, 37, 38, 39, 40, 41, 42]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EQ, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NOT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Repetition(44, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([33, 45]),
                new \Phplrt\Parser\Grammar\Concatenation([35]),
                new \Phplrt\Parser\Grammar\Concatenation([35, 43]),
                new \Phplrt\Parser\Grammar\Optional(48),
                new \Phplrt\Parser\Grammar\Alternation([49, 54]),
                new \Phplrt\Parser\Grammar\Concatenation([50, 51, 53]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Repetition(52, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([35, 50]),
                new \Phplrt\Parser\Grammar\Optional(35),
                new \Phplrt\Parser\Grammar\Concatenation([33, 49]),
                new \Phplrt\Parser\Grammar\Concatenation([50, 35, 56]),
                new \Phplrt\Parser\Grammar\Optional(49),
                new \Phplrt\Parser\Grammar\Optional(58),
                new \Phplrt\Parser\Grammar\Alternation([59, 63, 86, 98, 110]),
                new \Phplrt\Parser\Grammar\Concatenation([60, 61]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, true),
                new \Phplrt\Parser\Grammar\Alternation([62, 49]),
                new \Phplrt\Parser\Grammar\Concatenation([35, 56]),
                new \Phplrt\Parser\Grammar\Concatenation([11, 64, 81, 82]),
                new \Phplrt\Parser\Grammar\Optional(65),
                new \Phplrt\Parser\Grammar\Concatenation([66, 77, 80]),
                new \Phplrt\Parser\Grammar\Concatenation([0, 67, 69, 71, 75]),
                new \Phplrt\Parser\Grammar\Optional(68),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, true),
                new \Phplrt\Parser\Grammar\Optional(70),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ELLIPSIS, true),
                new \Phplrt\Parser\Grammar\Optional(72),
                new \Phplrt\Parser\Grammar\Alternation([73, 74]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_VARIABLE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Optional(76),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, true),
                new \Phplrt\Parser\Grammar\Repetition(78, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([79, 66]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Optional(79),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Optional(83),
                new \Phplrt\Parser\Grammar\Concatenation([84, 85]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([87, 97]),
                new \Phplrt\Parser\Grammar\Concatenation([88, 89, 94, 80, 96]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Concatenation([90]),
                new \Phplrt\Parser\Grammar\Alternation([91, 93]),
                new \Phplrt\Parser\Grammar\Concatenation([92, 93]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Alternation([50, 0]),
                new \Phplrt\Parser\Grammar\Repetition(95, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([79, 90]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Predicate(11, false),
                new \Phplrt\Parser\Grammar\Concatenation([99, 63]),
                new \Phplrt\Parser\Grammar\Concatenation([88, 100, 107, 80, 109]),
                new \Phplrt\Parser\Grammar\Concatenation([101]),
                new \Phplrt\Parser\Grammar\Concatenation([35, 102]),
                new \Phplrt\Parser\Grammar\Repetition(103, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([104, 105]),
                new \Phplrt\Parser\Grammar\Concatenation([35, 0]),
                new \Phplrt\Parser\Grammar\Concatenation([106, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, false),
                new \Phplrt\Parser\Grammar\Repetition(108, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([79, 101]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([111, 112, 80, 133]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([113, 132]),
                new \Phplrt\Parser\Grammar\Concatenation([114, 128]),
                new \Phplrt\Parser\Grammar\Concatenation([115, 126]),
                new \Phplrt\Parser\Grammar\Alternation([116, 125]),
                new \Phplrt\Parser\Grammar\Concatenation([117, 122, 84, 124]),
                new \Phplrt\Parser\Grammar\Alternation([118, 9]),
                new \Phplrt\Parser\Grammar\Concatenation([35, 119]),
                new \Phplrt\Parser\Grammar\Predicate(120, true),
                new \Phplrt\Parser\Grammar\Concatenation([121, 84]),
                new \Phplrt\Parser\Grammar\Optional(6),
                new \Phplrt\Parser\Grammar\Optional(123),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, true),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Repetition(127, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([79, 115]),
                new \Phplrt\Parser\Grammar\Optional(129),
                new \Phplrt\Parser\Grammar\Concatenation([79, 130]),
                new \Phplrt\Parser\Grammar\Concatenation([70, 131]),
                new \Phplrt\Parser\Grammar\Optional(87),
                new \Phplrt\Parser\Grammar\Optional(130),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(135, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([136, 137, 138]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Optional(0),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(140, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([141, 142]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, false),
                new \Phplrt\Parser\Grammar\Concatenation([4]),
                new \Phplrt\Parser\Grammar\Repetition(144, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([145, 146]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Concatenation([3]),
                new \Phplrt\Parser\Grammar\Optional(148),
                new \Phplrt\Parser\Grammar\Concatenation([149, 151, 6, 152, 153, 154]),
                new \Phplrt\Parser\Grammar\Concatenation([38, 150]),
                new \Phplrt\Parser\Grammar\Optional(39),
                new \Phplrt\Parser\Grammar\Alternation([0, 72]),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([72, 148]),
            ],
            initial: 0,
            reducers: [
                0 => $this->reduceType(...),
                2 => $this->reduceUnionType(...),
                3 => $this->reduceIntersectionType(...),
                5 => self::reduceNullableType(...),
                8 => $this->reduceListOrOffsetType(...),
                13 => self::reduceThisType(...),
                14 => $this->reduceLiteralType(...),
                17 => self::reduceDoubleQuotedStringLiteralType(...),
                18 => self::reduceSingleQuotedStringLiteralType(...),
                19 => self::reduceFloatLiteralType(...),
                20 => self::reduceIntLiteralType(...),
                25 => self::reduceTrueLiteralType(...),
                26 => self::reduceFalseLiteralType(...),
                27 => self::reduceNullLiteralType(...),
                28 => $this->reduceNamedType(...),
                29 => self::reduceNameOrMask(...),
                32 => self::reduceFullQualifiedName(...),
                35 => self::reduceIdentifier(...),
                46 => self::reduceRelativeName(...),
                50 => self::reduceWildcardType(...),
                54 => self::reduceNamespacedMask(...),
                64 => self::reduceCallableParameters(...),
                66 => self::reduceCallableParameter(...),
                72 => self::reduceVariable(...),
                87 => $this->reduceTemplateArguments(...),
                90 => $this->reduceTemplateArgument(...),
                92 => self::reduceIdentifierWithExtraSpace(...),
                99 => $this->reduceTemplateParameters(...),
                101 => self::reduceTemplateParameter(...),
                104 => self::reduceTemplateBoundEdge(...),
                110 => $this->reduceShapeFields(...),
                114 => self::reduceShapeFieldsList(...),
                116 => self::reduceExplicitField(...),
                125 => self::reduceImplicitField(...),
                135 => self::reduceListOrOffsetSuffix(...),
                149 => self::reduceTernaryExpressionOperator(...),
            ],
            lookahead: [
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    15 => true,
                ],
                [
                    15 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                ],
                [
                    18 => true,
                ],
                [
                    19 => true,
                ],
                [
                    26 => true,
                ],
                [
                    3 => true,
                    true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    3 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    28 => true,
                    true,
                ],
                [
                    28 => true,
                ],
                [
                    29 => true,
                ],
                [
                    30 => true,
                ],
                [
                    31 => true,
                    true,
                    true,
                    true,
                ],
                [
                    31 => true,
                ],
                [
                    32 => true,
                ],
                [
                    33 => true,
                ],
                [
                    34 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    5 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    7 => true,
                ],
                [
                    6 => true,
                ],
                [
                    1 => true,
                ],
                [
                    2 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    5 => true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    8 => true,
                    25 => true,
                ],
                [
                    25 => true,
                ],
                [
                    25 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    25 => true,
                ],
                null,
                null,
                [
                    11 => true,
                    13 => true,
                    16 => true,
                    18 => true,
                ],
                [
                    11 => true,
                ],
                [
                    11 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    22 => true,
                ],
                null,
                [
                    23 => true,
                ],
                null,
                [
                    26 => true,
                    true,
                ],
                [
                    27 => true,
                ],
                [
                    26 => true,
                ],
                null,
                [
                    24 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    10 => true,
                ],
                null,
                [
                    19 => true,
                ],
                null,
                [
                    12 => true,
                ],
                [
                    12 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    6 => true,
                ],
                [
                    6 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    14 => true,
                ],
                null,
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    24 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    24 => true,
                ],
                [
                    24 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    14 => true,
                ],
                [
                    16 => true,
                ],
                [
                    16 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    12 => true,
                    15 => true,
                ],
                null,
                null,
                [
                    15 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    10 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    23 => true,
                ],
                null,
                null,
                [
                    17 => true,
                ],
                null,
                [
                    20 => true,
                ],
                [
                    20 => true,
                ],
                null,
                [
                    21 => true,
                ],
                null,
                [
                    22 => true,
                ],
                [
                    22 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    9 => true,
                ],
                [
                    9 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    1 => true,
                ],
                [
                    1 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    12 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    26 => true,
                    true,
                ],
            ],
            kept: [
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
            ],
            choicePrediction: [
                [
                    1 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    15 => [
                        1,
                    ],
                    18 => [
                        1,
                    ],
                    25 => [
                        1,
                    ],
                    28 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    27 => [
                        155,
                    ],
                ],
                4 => [
                    15 => [
                        5,
                    ],
                    1 => [
                        8,
                    ],
                    2 => [
                        8,
                    ],
                    3 => [
                        8,
                    ],
                    4 => [
                        8,
                    ],
                    5 => [
                        8,
                    ],
                    6 => [
                        8,
                    ],
                    7 => [
                        8,
                    ],
                    8 => [
                        8,
                    ],
                    18 => [
                        8,
                    ],
                    25 => [
                        8,
                    ],
                    [
                        8,
                    ],
                    28 => [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                ],
                9 => [
                    18 => [
                        10,
                    ],
                    26 => [
                        13,
                    ],
                    3 => [
                        14,
                        28,
                    ],
                    4 => [
                        14,
                        28,
                    ],
                    5 => [
                        14,
                        28,
                    ],
                    28 => [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    1 => [
                        28,
                    ],
                    2 => [
                        28,
                    ],
                    6 => [
                        28,
                    ],
                    7 => [
                        28,
                    ],
                    8 => [
                        28,
                    ],
                    25 => [
                        28,
                    ],
                ],
                14 => [
                    3 => [
                        15,
                    ],
                    [
                        15,
                    ],
                    28 => [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        15,
                    ],
                    5 => [
                        27,
                    ],
                ],
                [
                    28 => [
                        16,
                    ],
                    [
                        16,
                    ],
                    [
                        19,
                    ],
                    [
                        20,
                    ],
                    [
                        20,
                    ],
                    [
                        20,
                    ],
                    [
                        20,
                    ],
                    3 => [
                        25,
                    ],
                    4 => [
                        26,
                    ],
                ],
                [
                    28 => [
                        17,
                    ],
                    [
                        18,
                    ],
                ],
                20 => [
                    31 => [
                        21,
                    ],
                    [
                        22,
                    ],
                    [
                        23,
                    ],
                    [
                        24,
                    ],
                ],
                29 => [
                    1 => [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    [
                        30,
                    ],
                    25 => [
                        55,
                    ],
                ],
                31 => [
                    8 => [
                        32,
                    ],
                    1 => [
                        46,
                    ],
                    2 => [
                        46,
                    ],
                    3 => [
                        46,
                    ],
                    4 => [
                        46,
                    ],
                    5 => [
                        46,
                    ],
                    6 => [
                        46,
                    ],
                    7 => [
                        46,
                    ],
                ],
                35 => [
                    7 => [
                        36,
                    ],
                    6 => [
                        37,
                    ],
                    1 => [
                        38,
                    ],
                    2 => [
                        39,
                    ],
                    3 => [
                        40,
                    ],
                    4 => [
                        41,
                    ],
                    5 => [
                        42,
                    ],
                ],
                48 => [
                    25 => [
                        49,
                    ],
                    8 => [
                        54,
                    ],
                ],
                58 => [
                    11 => [
                        59,
                    ],
                    18 => [
                        63,
                    ],
                    13 => [
                        86,
                        98,
                    ],
                    16 => [
                        110,
                    ],
                ],
                61 => [
                    1 => [
                        62,
                    ],
                    [
                        62,
                    ],
                    [
                        62,
                    ],
                    [
                        62,
                    ],
                    [
                        62,
                    ],
                    [
                        62,
                    ],
                    [
                        62,
                    ],
                    25 => [
                        49,
                    ],
                ],
                72 => [
                    27 => [
                        73,
                    ],
                    26 => [
                        74,
                    ],
                ],
                90 => [
                    1 => [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    7 => [
                        93,
                    ],
                    [
                        93,
                    ],
                    15 => [
                        93,
                    ],
                    18 => [
                        93,
                    ],
                    25 => [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                    [
                        93,
                    ],
                ],
                93 => [
                    1 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    15 => [
                        0,
                    ],
                    18 => [
                        0,
                    ],
                    26 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                ],
                103 => [
                    1 => [
                        104,
                    ],
                    [
                        104,
                    ],
                    [
                        104,
                    ],
                    [
                        104,
                    ],
                    [
                        104,
                    ],
                    [
                        104,
                    ],
                    [
                        104,
                    ],
                    24 => [
                        105,
                    ],
                ],
                115 => [
                    15 => [
                        125,
                    ],
                    27 => [
                        125,
                    ],
                ],
                117 => [
                    8 => [
                        9,
                    ],
                    18 => [
                        9,
                    ],
                    25 => [
                        9,
                    ],
                    [
                        9,
                    ],
                    28 => [
                        9,
                    ],
                    [
                        9,
                    ],
                    [
                        9,
                    ],
                    [
                        9,
                    ],
                    [
                        9,
                    ],
                    [
                        9,
                    ],
                    [
                        9,
                    ],
                ],
                151 => [
                    1 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    15 => [
                        0,
                    ],
                    18 => [
                        0,
                    ],
                    25 => [
                        0,
                    ],
                    28 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                ],
            ],
            expectations: [
                'T_WHITESPACE',
                'T_EQ',
                'T_NOT',
                'T_TRUE_LITERAL',
                'T_FALSE_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_FLOAT_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
                '/[^\\s]++/',
            ],
            messages: [
                7 => 'Syntax error, unexpected {token}, a nullable type must carry the type it makes nullable, for example "?T"',
                12 => 'Syntax error, unexpected {token}, a group must be closed with a bracket ")"',
                34 => 'Syntax error, unexpected {token}, a name must carry a segment after the separator, for example "\\Some"',
                45 => 'Syntax error, unexpected {token}, a name must carry a segment after the separator, for example "Some\\Any"',
                61 => 'Syntax error, unexpected {token}, a class constant must carry a name after the double colon, for example "Some::CONST"',
                81 => 'Syntax error, unexpected {token}, a parameter list must be closed with a bracket ")"',
                85 => 'Syntax error, unexpected {token}, a callable must carry a type after the colon ":"',
                89 => 'Syntax error, unexpected {token}, an argument list must carry at least one argument',
                96 => 'Syntax error, unexpected {token}, an argument list must be closed with a bracket ">"',
                100 => 'Syntax error, unexpected {token}, a parameter list must carry at least one parameter',
                109 => 'Syntax error, unexpected {token}, a parameter list must be closed with a bracket ">"',
                124 => 'Syntax error, unexpected {token}, a shape field must carry a type after the colon ":"',
                133 => 'Syntax error, unexpected {token}, a shape must be closed with a brace "}"',
                138 => 'Syntax error, unexpected {token}, an offset must be closed with a bracket "]"',
                142 => 'Syntax error, unexpected {token}, an intersection type must carry a type after the ampersand "&", for example "T&U"',
                146 => 'Syntax error, unexpected {token}, a union type must carry a type after the vertical bar "|", for example "T|U"',
                152 => 'Syntax error, unexpected {token}, a condition must carry the type it is true of',
                'Syntax error, unexpected {token}, a condition must be parted with a colon ":"',
                'Syntax error, unexpected {token}, a condition must carry the type it is false of',
            ],
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    private function reduceType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->conditions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('conditional expressions', $source, $offset);
        }

        $condition = $children[1]
            ? new Type\Condition\NotEqualConditionNode($children[0], $children[2], $offset)
            : new Type\Condition\EqualConditionNode($children[0], $children[2], $offset);

        return new Type\TernaryExpressionNode(
            $condition,
            $children[3],
            $children[4],
            $offset,
        );
    }

    private function reduceUnionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->unions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('union types', $source, $offset);
        }

        $statement = new Type\UnionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private function reduceIntersectionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->intersections === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('intersection types', $source, $offset);
        }

        $statement = new Type\IntersectionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private static function reduceNullableType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\NullableTypeNode($children[0], $offset);
    }

    private function reduceListOrOffsetType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $statement = $children[0];
        $count = \count($children);

        for ($i = 1; $i < $count; ++$i) {
            $child = $children[$i];

            switch (true) {
                case $child === true:
                    if ($this->features->lists === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('square bracket list types', $source, $offset);
                    }

                    $statement = new Type\TypesListNode($statement, $offset);
                    break;
                case $child instanceof Type\TypeNode:
                    if ($this->features->offsets === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('type offsets', $source, $offset);
                    }

                    $statement = new Type\TypeOffsetAccessNode($statement, $child, $offset);
                    break;
                default:
                    throw Exception\InternalSemanticException::becauseSubNodeIsUnexpected(
                        \get_debug_type($child),
                        $source,
                        $offset,
                    );
            }
        }

        return $statement;
    }

    private static function reduceThisType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\ThisNode($offset);
    }

    private function reduceLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->literals === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('literal values', $source, $offset);
        }

        return $children;
    }

    private static function reduceDoubleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            StringDecoder::unpackAndDecode($children->value, true),
            $children->value,
            $offset,
        );
    }

    private static function reduceSingleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            StringDecoder::unpackAndDecode($children->value, false),
            $children->value,
            $offset,
        );
    }

    private static function reduceFloatLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\FloatLiteralNode(
            FloatDecoder::decode($children->value),
            $children->value,
            $offset,
        );
    }

    private static function reduceIntLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $decoded = IntDecoder::decode($children->value);

        return new Type\Literal\IntLiteralNode(
            $decoded->value,
            $children->value,
            $decoded->decimal,
            $offset,
        );
    }

    private static function reduceTrueLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(true, $children->value, $offset);
    }

    private static function reduceFalseLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(false, $children->value, $offset);
    }

    private static function reduceNullLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\NullLiteralNode(
            $children->value,
            $offset,
        );
    }

    private function reduceNamedType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $head = $children[0];
        $suffix = $children[1] ?? null;

        if ($head instanceof Type\ConstMaskNode) {
            if ($suffix !== null) {
                throw Exception\ConstMaskException::becauseNothingFollowsAMask($source, $offset);
            }

            return $head;
        }

        switch (true) {
            // Some\Any
            case $suffix === null:
                return new Type\NamedTypeNode($children[0], null, null, $offset);

                // Some\Any<T, U>
            case $suffix instanceof Type\Template\TemplateArgumentListNode:
                return new Type\NamedTypeNode($children[0], $suffix, null, $offset);

                // Some\Any{name: T, ...<K, V>}
            case $suffix instanceof Type\Shape\FieldsListNode:
                return new Type\NamedTypeNode($children[0], $children[2] ?? null, $suffix, $offset);

                // Some\Any(T, U): V
            case $suffix instanceof Type\Callable\CallableParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $source, $offset);
                }

                return new Type\CallableTypeNode($children[0], $suffix, $children[2] ?? null, null, $offset);

                // Some\Any<T, U>(T): U
            case $suffix instanceof Type\Template\TemplateParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $source, $offset);
                }

                return new Type\CallableTypeNode($children[0], $children[2], $children[3] ?? null, $suffix, $offset);

                // Some\Any::CONST, Some\Any::CONST_* and Some\Any::*
            default:
                if (\count($children) === 3 && $children[2] instanceof Type\Identifier) {
                    return new Type\ClassConstNode($children[0], $children[2], $offset);
                }

                return new Type\ClassConstMaskNode(
                    $children[0],
                    new Type\MaskNode(\array_slice($children, 2), $children[2]->offset),
                    $offset,
                );
        }
    }

    private static function reduceNameOrMask(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $head = $children[0];

        // "*_SOME"
        if (!$head instanceof Type\Name) {
            return new Type\ConstMaskNode(new Type\MaskNode($children, $offset), false, $offset);
        }

        // "Some\Any"
        if (!isset($children[1])) {
            return $head;
        }

        $parts = $head->parts;

        if ($children[1] instanceof Type\MaskNode) {
            // "Some\Any\*"
            $mask = $children[1];
        } else {
            // "Some\Any\SOME_*"
            $segment = \array_pop($parts);
            $mask = new Type\MaskNode([$segment, ...\array_slice($children, 1)], $segment->offset);
        }

        return new Type\ConstMaskNode(
            $mask,
            $parts === []
                ? $head->isFullyQualified
                : new Type\Name($parts, $head->isFullyQualified, $head->offset),
            $offset,
        );
    }

    private static function reduceFullQualifiedName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, true, $offset);
    }

    private static function reduceIdentifier(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(
            $children->id === self::T_NAME_WITH_SPACE
                ? \rtrim($children->value)
                : $children->value,
            $offset,
        );
    }

    private static function reduceRelativeName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, false, $offset);
    }

    private static function reduceWildcardType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\WildcardNode($offset);
    }

    private static function reduceNamespacedMask(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\MaskNode($children, $offset);
    }

    private static function reduceCallableParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Callable\CallableParameterListNode($children, $offset);
    }

    private static function reduceCallableParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $parameter = new Type\Callable\CallableParameterNode(
            $children[0],
            null,
            false,
            false,
            false,
            $offset,
        );

        for ($i = 1, $count = \count($children); $i < $count; ++$i) {
            $child = $children[$i];

            if ($child instanceof Type\VariableNode) {
                $parameter->name = $child;

                continue;
            }

            switch ($child->id) {
                case self::T_AMP:
                    $parameter->isOutput = true;
                    break;

                case self::T_ELLIPSIS:
                    $parameter->isVariadic = true;
                    break;

                default:
                    if ($parameter->isVariadic) {
                        throw Exception\VariadicWithDefaultException::becauseVariadicHasDefault($source, $offset);
                    }

                    $parameter->isOptional = true;
            }
        }

        return $parameter;
    }

    private static function reduceVariable(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\VariableNode(
            new Type\Identifier(\substr($children->value, 1), $offset),
            $offset,
        );
    }

    private function reduceTemplateArguments(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template arguments', $source, $offset);
        }

        return new Type\Template\TemplateArgumentListNode($children, $offset);
    }

    private function reduceTemplateArgument(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\is_array($children)) {
            if ($this->features->hints === false) {
                throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template argument hints', $source, $offset);
            }

            return new Type\Template\TemplateArgumentNode($children[1], $children[0], $offset);
        }

        return new Type\Template\TemplateArgumentNode($children, null, $offset);
    }

    private static function reduceIdentifierWithExtraSpace(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(\rtrim($children->value), $offset);
    }

    private function reduceTemplateParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template parameters', $source, $offset);
        }

        return new Type\Template\TemplateParameterListNode($children, $offset);
    }

    private static function reduceTemplateParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $upper = $lower = $default = null;

        foreach (\array_slice($children, 1) as $limit) {
            if (!$limit instanceof Type\Template\TemplateBoundEdgeNode) {
                if ($default !== null) {
                    throw Exception\TemplateBoundException::becauseBoundIsDuplicated('default', $source, $limit->offset);
                }

                $default = $limit;

                continue;
            }

            if ($default !== null) {
                throw Exception\TemplateBoundException::becauseDefaultIsNotWrittenLast($source, $limit->operator->offset);
            }

            switch ($limit->operator->value) {
                case 'of':
                case 'as':
                    if ($upper !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('upper bound', $source, $limit->offset);
                    }

                    $upper = $limit;
                    break;

                case 'super':
                    if ($lower !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('lower bound', $source, $limit->offset);
                    }

                    $lower = $limit;
                    break;

                default:
                    throw Exception\TemplateBoundException::becauseOperatorIsUnknown(
                        $limit->operator->value,
                        $source,
                        $limit->operator->offset,
                    );
            }
        }

        return new Type\Template\TemplateParameterNode($children[0], $upper, $lower, $default, $offset);
    }

    private static function reduceTemplateBoundEdge(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Template\TemplateBoundEdgeNode($children[0], $children[1], $offset);
    }

    private function reduceShapeFields(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $count = \count($children);

        if ($count === 0) {
            return [new Type\Shape\FieldsListNode([], true, $offset)];
        }

        if ($this->features->shapes === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('shape fields', $source, $offset);
        }

        $parameters = null;

        // The "...<K, V>" suffix
        if ($children[$count - 1] instanceof Type\Template\TemplateArgumentListNode) {
            $parameters = $children[$count - 1];
            --$count;
        }

        if ($children[0] instanceof Type\Shape\FieldsListNode) {
            $fields = $children[0];
            $unsealed = $count > 1;
        } else {
            $fields = new Type\Shape\FieldsListNode([], true, $offset);
            $unsealed = $count > 0;
        }

        if ($unsealed) {
            $fields->isSealed = false;
        }

        if ($parameters === null) {
            return [$fields];
        }

        return [$fields, $parameters];
    }

    private static function reduceShapeFieldsList(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $explicit = false;
        $implicit = false;
        $indexed = [];

        foreach ($children as $field) {
            if (!$field instanceof Type\Shape\ExplicitFieldNode) {
                $implicit = true;

                continue;
            }

            $explicit = true;

            if (!$field instanceof Type\Shape\SimpleFieldNodeInterface) {
                continue;
            }

            $key = $field->getIndex();

            if (isset($indexed[$key])) {
                throw Exception\ShapeFieldDuplicationException::becauseShapeFieldIsDuplicated($key, $source, $field->offset);
            }

            $indexed[$key] = true;
        }

        if ($explicit && $implicit) {
            throw Exception\ShapeKeysMixingException::becauseShapeKeysAreMixed($source, $offset);
        }

        return new Type\Shape\FieldsListNode($children, true, $offset);
    }

    private static function reduceExplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $count = \count($children);
        $name = $children[0];
        $value = $children[$count - 1];

        $optional = $count === 3;

        return match (true) {
            // "a", "true" and "null"
            $name instanceof Type\Identifier
                => new Type\Shape\NamedFieldNode($name, $value, $optional, $offset),
            $name instanceof Type\Literal\IntLiteralNode,
            $name instanceof Type\Literal\StringLiteralNode
                => new Type\Shape\ScalarFieldNode($name, $value, $optional, $offset),
            // "Some::CONST", "Some::CONST_*" and "JSON_*"
            $name instanceof Type\ClassConstNode,
            $name instanceof Type\ClassConstMaskNode,
            $name instanceof Type\ConstMaskNode
                => new Type\Shape\ComplexFieldNode($name, $value, $optional, $offset),
            default => throw Exception\ShapeKeyException::becauseKeyIsNotAName($source, $name->offset),
        };
    }

    private static function reduceImplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Shape\ImplicitFieldNode($children[0], false, $offset);
    }

    private static function reduceListOrOffsetSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return $children[0] ?? true;
    }

    private static function reduceTernaryExpressionOperator(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \count($children) === 2;
    }
}
