<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.0.0
 */

declare(strict_types=1);

namespace TypeLang\Parser\Internal;

use TypeLang\Parser\Exception;
use TypeLang\Type;

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

/**
 * @template TResult of mixed = mixed
 *
 * @template-implements \Phplrt\Contracts\Parser\ParserInterface<TResult>
 */
abstract class CompilerExecutor implements \Phplrt\Contracts\Parser\ParserInterface
{
    /** @var int */
    public const T_WHITESPACE = 0;
    /** @var int */
    public const T_NEQ = 1;
    /** @var int */
    public const T_EQ = 2;
    /** @var int */
    public const T_BOOL_LITERAL = 3;
    /** @var int */
    public const T_NULL_LITERAL = 4;
    /** @var int */
    public const T_NAME_WITH_SPACE = 5;
    /** @var int */
    public const T_NAME = 6;
    /** @var int */
    public const T_NS_DELIMITER = 7;
    /** @var int */
    public const T_OR = 8;
    /** @var int */
    public const T_COMMA = 9;
    /** @var int */
    public const T_DOUBLE_COLON = 10;
    /** @var int */
    public const T_COLON = 11;
    /** @var int */
    public const T_LTE = 12;
    /** @var int */
    public const T_GTE = 13;
    /** @var int */
    public const T_ANGLE_BRACKET_OPEN = 14;
    /** @var int */
    public const T_ANGLE_BRACKET_CLOSE = 15;
    /** @var int */
    public const T_QMARK = 16;
    /** @var int */
    public const T_BRACE_OPEN = 17;
    /** @var int */
    public const T_BRACE_CLOSE = 18;
    /** @var int */
    public const T_PARENTHESIS_OPEN = 19;
    /** @var int */
    public const T_PARENTHESIS_CLOSE = 20;
    /** @var int */
    public const T_SQUARE_BRACKET_OPEN = 21;
    /** @var int */
    public const T_SQUARE_BRACKET_CLOSE = 22;
    /** @var int */
    public const T_AMP = 23;
    /** @var int */
    public const T_ELLIPSIS = 24;
    /** @var int */
    public const T_ASSIGN = 25;
    /** @var int */
    public const T_ASTERISK = 26;
    /** @var int */
    public const T_THIS = 27;
    /** @var int */
    public const T_VARIABLE = 28;
    /** @var int */
    public const T_DQ_STRING_LITERAL = 29;
    /** @var int */
    public const T_SQ_STRING_LITERAL = 30;
    /** @var int */
    public const T_PFX_FLOAT_LITERAL = 31;
    /** @var int */
    public const T_SFX_FLOAT_LITERAL = 32;
    /** @var int */
    public const T_EXP_LITERAL = 33;
    /** @var int */
    public const T_BIN_INT_LITERAL = 34;
    /** @var int */
    public const T_OCT_INT_LITERAL = 35;
    /** @var int */
    public const T_HEX_INT_LITERAL = 36;
    /** @var int */
    public const T_DEC_INT_LITERAL = 37;
    /** @var int */
    public const T_COMMENT = 38;
    /** @var int */
    public const T_DOC_COMMENT = 39;

    /**
     * @var \Phplrt\Contracts\Parser\ParserInterface<TResult>
     */
    protected readonly \Phplrt\Contracts\Parser\ParserInterface $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:(?i:is\\h++not)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:1))|(?:(?:(?i:is)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:2))|(?:(?:(?i:true|false)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:3))|(?:(?:(?i:null)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:4))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+\\s++)(*MARK:5))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+)(*MARK:6))|(?:(?:\\\\)(*MARK:7))|(?:(?:\\|)(*MARK:8))|(?:(?:,)(*MARK:9))|(?:(?:::)(*MARK:10))|(?:(?::)(*MARK:11))|(?:(?:<=)(*MARK:12))|(?:(?:>=)(*MARK:13))|(?:(?:<)(*MARK:14))|(?:(?:>)(*MARK:15))|(?:(?:\\?)(*MARK:16))|(?:(?:\\{)(*MARK:17))|(?:(?:\\})(*MARK:18))|(?:(?:\\()(*MARK:19))|(?:(?:\\))(*MARK:20))|(?:(?:\\[)(*MARK:21))|(?:(?:\\])(*MARK:22))|(?:(?:&)(*MARK:23))|(?:(?:\\.\\.\\.)(*MARK:24))|(?:(?:=)(*MARK:25))|(?:(?:\\*)(*MARK:26))|(?:(?:\\$this\\b)(*MARK:27))|(?:(?:\\$(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+)(*MARK:28))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:29))|(?:(?:\'[^\'\\\\]*+(?:\\\\.[^\'\\\\]*+)*+\')(*MARK:30))|(?:(?:-?(?:[0-9])++\\.(?:[0-9])*+(?:(?:[eE]-?(?:[0-9])++))?)(*MARK:31))|(?:(?:-?(?:[0-9])*+\\.(?:[0-9])++(?:(?:[eE]-?(?:[0-9])++))?)(*MARK:32))|(?:(?:-?(?:[0-9])++(?:[eE]-?(?:[0-9])++))(*MARK:33))|(?:(?:-?0[bB][01_]++)(*MARK:34))|(?:(?:-?0[oO][0-7_]++)(*MARK:35))|(?:(?:-?0[xX][0-9a-fA-F_]++)(*MARK:36))|(?:(?:-?(?:[0-9])[0-9_]*+)(*MARK:37))|(?:(?:(?:\\/\\/|\\#)[^\\r\\n]*+)(*MARK:38))|(?:(?:\\/\\*.*?\\*\\/)(*MARK:39))|(?:(?:[^\\s]++)(*MARK:40)))/Ssum',
            channels: [
                'Hidden',
                38 => 'Hidden',
                'Hidden',
                'Unknown',
            ],
            names: [
                'T_WHITESPACE',
                'T_NEQ',
                'T_EQ',
                'T_BOOL_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_LTE',
                'T_GTE',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_PFX_FLOAT_LITERAL',
                'T_SFX_FLOAT_LITERAL',
                'T_EXP_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Alternation([1, 125]),
                new \Phplrt\Parser\Grammar\Concatenation([2, 116]),
                new \Phplrt\Parser\Grammar\Concatenation([3, 113]),
                new \Phplrt\Parser\Grammar\Concatenation([4, 110]),
                new \Phplrt\Parser\Grammar\Alternation([5, 7]),
                new \Phplrt\Parser\Grammar\Concatenation([6, 7]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, false),
                new \Phplrt\Parser\Grammar\Concatenation([8, 105]),
                new \Phplrt\Parser\Grammar\Alternation([9, 12, 13, 28]),
                new \Phplrt\Parser\Grammar\Concatenation([10, 0, 11]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Alternation([14, 17, 21, 26, 27]),
                new \Phplrt\Parser\Grammar\Alternation([15, 16]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Alternation([18, 19, 20]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PFX_FLOAT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SFX_FLOAT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EXP_LITERAL, true),
                new \Phplrt\Parser\Grammar\Alternation([22, 23, 24, 25]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BIN_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OCT_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_HEX_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DEC_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BOOL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Concatenation([29, 41]),
                new \Phplrt\Parser\Grammar\Alternation([30, 40]),
                new \Phplrt\Parser\Grammar\Concatenation([31, 32, 38]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NS_DELIMITER, false),
                new \Phplrt\Parser\Grammar\Alternation([33, 34, 35, 36, 37]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EQ, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BOOL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Repetition(39, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([31, 32]),
                new \Phplrt\Parser\Grammar\Concatenation([32, 38]),
                new \Phplrt\Parser\Grammar\Optional(42),
                new \Phplrt\Parser\Grammar\Alternation([43, 44, 50, 71, 80]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Concatenation([45, 46]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, false),
                new \Phplrt\Parser\Grammar\Alternation([47, 49]),
                new \Phplrt\Parser\Grammar\Concatenation([32, 48]),
                new \Phplrt\Parser\Grammar\Optional(49),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Concatenation([10, 51, 11, 68]),
                new \Phplrt\Parser\Grammar\Optional(52),
                new \Phplrt\Parser\Grammar\Concatenation([53, 64, 67]),
                new \Phplrt\Parser\Grammar\Concatenation([0, 54, 56, 58, 62]),
                new \Phplrt\Parser\Grammar\Optional(55),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, true),
                new \Phplrt\Parser\Grammar\Optional(57),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ELLIPSIS, true),
                new \Phplrt\Parser\Grammar\Optional(59),
                new \Phplrt\Parser\Grammar\Alternation([60, 61]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_VARIABLE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Optional(63),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, true),
                new \Phplrt\Parser\Grammar\Repetition(65, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([66, 53]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Optional(66),
                new \Phplrt\Parser\Grammar\Optional(69),
                new \Phplrt\Parser\Grammar\Concatenation([70, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([72, 73, 77, 67, 79]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([74, 76]),
                new \Phplrt\Parser\Grammar\Concatenation([75, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Repetition(78, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([66, 73]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([81, 82, 67, 104]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([83, 103]),
                new \Phplrt\Parser\Grammar\Concatenation([84, 99]),
                new \Phplrt\Parser\Grammar\Concatenation([85, 97]),
                new \Phplrt\Parser\Grammar\Alternation([86, 96]),
                new \Phplrt\Parser\Grammar\Concatenation([87, 94, 70, 0]),
                new \Phplrt\Parser\Grammar\Alternation([88, 92, 21, 14]),
                new \Phplrt\Parser\Grammar\Concatenation([32, 89]),
                new \Phplrt\Parser\Grammar\Predicate(90, true),
                new \Phplrt\Parser\Grammar\Concatenation([91, 70]),
                new \Phplrt\Parser\Grammar\Optional(6),
                new \Phplrt\Parser\Grammar\Concatenation([29, 93]),
                new \Phplrt\Parser\Grammar\Alternation([43, 44]),
                new \Phplrt\Parser\Grammar\Optional(95),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, true),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Repetition(98, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([66, 85]),
                new \Phplrt\Parser\Grammar\Optional(100),
                new \Phplrt\Parser\Grammar\Concatenation([66, 101]),
                new \Phplrt\Parser\Grammar\Concatenation([57, 102]),
                new \Phplrt\Parser\Grammar\Optional(71),
                new \Phplrt\Parser\Grammar\Optional(101),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(106, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([107, 108, 109]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Optional(0),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(111, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([112, 4]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, false),
                new \Phplrt\Parser\Grammar\Repetition(114, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([115, 3]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Optional(117),
                new \Phplrt\Parser\Grammar\Concatenation([118, 124, 6, 0, 70, 0]),
                new \Phplrt\Parser\Grammar\Alternation([35, 119, 120, 121, 122, 123]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NEQ, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_GTE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_LTE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_OPEN, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, true),
                new \Phplrt\Parser\Grammar\Alternation([0, 59]),
                new \Phplrt\Parser\Grammar\Concatenation([59, 117]),
            ],
            initial: 0,
            reducers: [
                0 => $this->reduceType(...),
                2 => $this->reduceUnionType(...),
                3 => $this->reduceIntersectionType(...),
                5 => self::reduceNullableType(...),
                7 => $this->reduceTypesList(...),
                12 => self::reduceThisLiteral(...),
                13 => $this->reduceLiteral(...),
                15 => $this->reduceDoubleQuotedStringLiteral(...),
                16 => $this->reduceSingleQuotedStringLiteral(...),
                17 => self::reduceFloatLiteral(...),
                21 => $this->reduceIntLiteral(...),
                26 => $this->reduceBoolLiteral(...),
                27 => self::reduceNullLiteral(...),
                28 => $this->reduceNamedType(...),
                30 => self::reduceFullQualifiedName(...),
                32 => self::reduceIdentifier(...),
                40 => self::reduceRelativeName(...),
                43 => self::reduceConstMaskSuffix(...),
                49 => self::reduceClassConstMaskSuffix(...),
                51 => self::reduceCallableParameters(...),
                53 => self::reduceCallableParameter(...),
                59 => self::reduceVariableLiteral(...),
                71 => $this->reduceTemplateArguments(...),
                73 => $this->reduceTemplateArgument(...),
                75 => self::reduceIdentifierWithExtraSpace(...),
                80 => $this->reduceShapeFields(...),
                84 => self::reduceShapeFieldsList(...),
                86 => self::reduceExplicitField(...),
                92 => self::reduceShapeConstantKey(...),
                96 => self::reduceImplicitField(...),
                106 => self::reduceTypeListOrOffsetSuffix(...),
            ],
            lookahead: [
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    16 => true,
                ],
                [
                    16 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    19 => true,
                    27 => true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    19 => true,
                ],
                [
                    19 => true,
                ],
                [
                    20 => true,
                ],
                [
                    27 => true,
                ],
                [
                    3 => true,
                    true,
                    29 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    29 => true,
                    true,
                ],
                [
                    29 => true,
                ],
                [
                    30 => true,
                ],
                [
                    31 => true,
                    true,
                    true,
                ],
                [
                    31 => true,
                ],
                [
                    32 => true,
                ],
                [
                    33 => true,
                ],
                [
                    34 => true,
                    true,
                    true,
                    true,
                ],
                [
                    34 => true,
                ],
                [
                    35 => true,
                ],
                [
                    36 => true,
                ],
                [
                    37 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    7 => true,
                ],
                [
                    7 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    6 => true,
                ],
                [
                    5 => true,
                ],
                [
                    2 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                null,
                [
                    7 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    10 => true,
                    14 => true,
                    17 => true,
                    19 => true,
                    26 => true,
                ],
                [
                    26 => true,
                ],
                [
                    10 => true,
                ],
                [
                    10 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    26 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    26 => true,
                ],
                [
                    19 => true,
                ],
                null,
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    23 => true,
                ],
                null,
                [
                    24 => true,
                ],
                null,
                [
                    27 => true,
                    true,
                ],
                [
                    28 => true,
                ],
                [
                    27 => true,
                ],
                null,
                [
                    25 => true,
                ],
                null,
                [
                    9 => true,
                ],
                [
                    9 => true,
                ],
                null,
                null,
                [
                    11 => true,
                ],
                [
                    11 => true,
                ],
                [
                    14 => true,
                ],
                [
                    14 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    5 => true,
                ],
                [
                    5 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    9 => true,
                ],
                [
                    15 => true,
                ],
                [
                    17 => true,
                ],
                [
                    17 => true,
                ],
                null,
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    29 => true,
                    true,
                    34 => true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    29 => true,
                    true,
                    34 => true,
                    true,
                    true,
                    true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    11 => true,
                    16 => true,
                ],
                null,
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    10 => true,
                    26 => true,
                ],
                null,
                [
                    16 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    9 => true,
                ],
                null,
                [
                    9 => true,
                ],
                [
                    24 => true,
                ],
                null,
                null,
                [
                    18 => true,
                ],
                null,
                [
                    21 => true,
                ],
                [
                    21 => true,
                ],
                null,
                [
                    22 => true,
                ],
                null,
                [
                    23 => true,
                ],
                [
                    23 => true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    12 => true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    12 => true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                ],
                [
                    13 => true,
                ],
                [
                    12 => true,
                ],
                [
                    14 => true,
                ],
                [
                    15 => true,
                ],
                [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    16 => true,
                    19 => true,
                    27 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    27 => true,
                    true,
                ],
            ],
            kept: [
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                true,
                true,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
            ],
            choicePrediction: [
                [
                    2 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    16 => [
                        1,
                    ],
                    19 => [
                        1,
                    ],
                    29 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    28 => [
                        125,
                    ],
                ],
                4 => [
                    16 => [
                        5,
                    ],
                    2 => [
                        7,
                    ],
                    3 => [
                        7,
                    ],
                    4 => [
                        7,
                    ],
                    5 => [
                        7,
                    ],
                    6 => [
                        7,
                    ],
                    7 => [
                        7,
                    ],
                    19 => [
                        7,
                    ],
                    27 => [
                        7,
                    ],
                    29 => [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                ],
                8 => [
                    19 => [
                        9,
                    ],
                    27 => [
                        12,
                    ],
                    3 => [
                        13,
                        28,
                    ],
                    4 => [
                        13,
                        28,
                    ],
                    29 => [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    2 => [
                        28,
                    ],
                    5 => [
                        28,
                    ],
                    6 => [
                        28,
                    ],
                    7 => [
                        28,
                    ],
                ],
                13 => [
                    29 => [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        17,
                    ],
                    [
                        17,
                    ],
                    [
                        17,
                    ],
                    [
                        21,
                    ],
                    [
                        21,
                    ],
                    [
                        21,
                    ],
                    [
                        21,
                    ],
                    3 => [
                        26,
                    ],
                    4 => [
                        27,
                    ],
                ],
                [
                    29 => [
                        15,
                    ],
                    [
                        16,
                    ],
                ],
                17 => [
                    31 => [
                        18,
                    ],
                    [
                        19,
                    ],
                    [
                        20,
                    ],
                ],
                21 => [
                    34 => [
                        22,
                    ],
                    [
                        23,
                    ],
                    [
                        24,
                    ],
                    [
                        25,
                    ],
                ],
                29 => [
                    7 => [
                        30,
                    ],
                    2 => [
                        40,
                    ],
                    3 => [
                        40,
                    ],
                    4 => [
                        40,
                    ],
                    5 => [
                        40,
                    ],
                    6 => [
                        40,
                    ],
                ],
                32 => [
                    6 => [
                        33,
                    ],
                    5 => [
                        34,
                    ],
                    2 => [
                        35,
                    ],
                    3 => [
                        36,
                    ],
                    4 => [
                        37,
                    ],
                ],
                42 => [
                    26 => [
                        43,
                    ],
                    10 => [
                        44,
                    ],
                    19 => [
                        50,
                    ],
                    14 => [
                        71,
                    ],
                    17 => [
                        80,
                    ],
                ],
                46 => [
                    2 => [
                        47,
                    ],
                    [
                        47,
                    ],
                    [
                        47,
                    ],
                    [
                        47,
                    ],
                    [
                        47,
                    ],
                    26 => [
                        49,
                    ],
                ],
                59 => [
                    28 => [
                        60,
                    ],
                    27 => [
                        61,
                    ],
                ],
                73 => [
                    2 => [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    6 => [
                        76,
                    ],
                    [
                        76,
                    ],
                    16 => [
                        76,
                    ],
                    19 => [
                        76,
                    ],
                    27 => [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                    [
                        76,
                    ],
                ],
                85 => [
                    16 => [
                        96,
                    ],
                    19 => [
                        96,
                    ],
                    27 => [
                        96,
                    ],
                    [
                        96,
                    ],
                    31 => [
                        96,
                    ],
                    [
                        96,
                    ],
                    [
                        96,
                    ],
                ],
                87 => [
                    2 => [
                        88,
                        92,
                    ],
                    [
                        88,
                        92,
                    ],
                    [
                        88,
                        92,
                    ],
                    [
                        88,
                        92,
                    ],
                    [
                        88,
                        92,
                    ],
                    [
                        92,
                    ],
                    34 => [
                        21,
                    ],
                    [
                        21,
                    ],
                    [
                        21,
                    ],
                    [
                        21,
                    ],
                    29 => [
                        14,
                    ],
                    30 => [
                        14,
                    ],
                ],
                93 => [
                    26 => [
                        43,
                    ],
                    10 => [
                        44,
                    ],
                ],
                118 => [
                    2 => [
                        35,
                    ],
                    1 => [
                        119,
                    ],
                    13 => [
                        120,
                    ],
                    12 => [
                        121,
                    ],
                    [
                        122,
                    ],
                    [
                        123,
                    ],
                ],
                124 => [
                    2 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    16 => [
                        0,
                    ],
                    19 => [
                        0,
                    ],
                    29 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                ],
            ],
            expectations: [
                'T_WHITESPACE',
                'T_NEQ',
                'T_EQ',
                'T_BOOL_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_LTE',
                'T_GTE',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_PFX_FLOAT_LITERAL',
                'T_SFX_FLOAT_LITERAL',
                'T_EXP_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
                '/[^\\s]++/',
            ],
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    private function reduceType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->conditions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('conditional expressions', $offset);
        }

        $condition = match ($children[1]->id) {
            self::T_EQ => new Type\Condition\EqualConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            self::T_NEQ => new Type\Condition\NotEqualConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            self::T_GTE => new Type\Condition\GreaterThanOrEqualConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            self::T_ANGLE_BRACKET_CLOSE => new Type\Condition\GreaterThanConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            self::T_LTE => new Type\Condition\LessThanOrEqualConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            self::T_ANGLE_BRACKET_OPEN => new Type\Condition\LessThanConditionNode(
                $children[0],
                $children[2],
                $offset,
            ),
            default => throw Exception\InvalidConditionalOperatorException::becauseConditionalOperatorIsInvalid(
                $children[1]->value,
                $offset,
            ),
        };

        return new Type\TernaryExpressionNode(
            $condition,
            $children[3],
            $children[4],
            $offset,
        );
    }

    private function reduceUnionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->unions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('union types', $offset);
        }

        // A logical statement takes an arbitrary number of types, so its
        // offset is assigned rather than passed to the constructor
        $statement = new Type\UnionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private function reduceIntersectionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->intersections === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('intersection types', $offset);
        }

        // A logical statement takes an arbitrary number of types, so its
        // offset is assigned rather than passed to the constructor
        $statement = new Type\IntersectionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private static function reduceNullableType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\NullableTypeNode($children[0], $offset);
    }

    private function reduceTypesList(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $statement = $children[0];
        $count = \count($children);

        for ($i = 1; $i < $count; ++$i) {
            $child = $children[$i];

            switch (true) {
                // In case of list type
                case $child === true:
                    if ($this->features->lists === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('square bracket list types', $offset);
                    }

                    $statement = new Type\TypesListNode($statement, $offset);
                    break;
                    // In case of offset access type
                case $child instanceof Type\TypeNode:
                    if ($this->features->offsets === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('type offsets', $offset);
                    }

                    $statement = new Type\TypeOffsetAccessNode($statement, $child, $offset);
                    break;
                default:
                    throw Exception\InternalSemanticException::becauseSubNodeIsUnexpected(
                        \get_debug_type($child),
                        $offset,
                    );
            }
        }

        return $statement;
    }

    private static function reduceThisLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\VariableLiteralNode(\substr($children->value, 1), $offset);
    }

    private function reduceLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if ($this->features->literals === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('literal values', $offset);
        }

        return $children;
    }

    private function reduceDoubleQuotedStringLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return $this->createDoubleQuotedString($children->value, $offset);
    }

    private function reduceSingleQuotedStringLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return $this->createSingleQuotedString($children->value, $offset);
    }

    private static function reduceFloatLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\FloatLiteralNode((float) $children->value, $children->value, $offset);
    }

    private function reduceIntLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return $this->createInt($children->value, $offset);
    }

    private function reduceBoolLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return $this->createBool($children->value, $offset);
    }

    private static function reduceNullLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\NullLiteralNode($children->value, $offset);
    }

    private function reduceNamedType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $suffix = $children[1] ?? null;

        switch (true) {
            // Some\Any<T, U>
            case $suffix instanceof Type\Template\TemplateArgumentListNode:
                return new Type\NamedTypeNode($children[0], $suffix, null, $offset);

                // Some\Any{name: T, ...<K, V>}
            case $suffix instanceof Type\Shape\FieldsListNode:
                return new Type\NamedTypeNode($children[0], $children[2] ?? null, $suffix, $offset);

                // Some\Any(T, U): V
            case $suffix instanceof Type\Callable\CallableParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $offset);
                }

                return new Type\CallableTypeNode($children[0], $suffix, $children[2] ?? null, $offset);

                // Some\Any::CONST and Some\Any::CONST_*
            case $suffix instanceof Type\Identifier:
                if (isset($children[2])) {
                    return new Type\ClassConstMaskNode($children[0], $suffix, $offset);
                }

                return new Type\ClassConstNode($children[0], $suffix, $offset);

                // Some\Any::*
            case $suffix === true:
                return new Type\ClassConstMaskNode($children[0], offset: $offset);

                // SOME_ANY_*
            case $suffix === false:
                return new Type\ConstMaskNode($children[0], $offset);

                // Some\Any
            default:
                return new Type\NamedTypeNode($children[0], null, null, $offset);
        }
    }

    private static function reduceFullQualifiedName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, true, $offset);
    }

    private static function reduceIdentifier(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        // Only a name written with a trailing space carries one, so the value of
        // every other token is the identifier itself
        return new Type\Identifier(
            $children->id === self::T_NAME_WITH_SPACE
                ? \rtrim($children->value)
                : $children->value,
            $offset,
        );
    }

    private static function reduceRelativeName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, false, $offset);
    }

    private static function reduceConstMaskSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return false;
    }

    private static function reduceClassConstMaskSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return true;
    }

    private static function reduceCallableParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Callable\CallableParameterListNode($children, $offset);
    }

    private static function reduceCallableParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $parameter = new Type\Callable\CallableParameterNode($children[0], offset: $offset);

        for ($i = 1, $count = \count($children); $i < $count; ++$i) {
            $child = $children[$i];

            if ($child instanceof Type\Literal\VariableLiteralNode) {
                $parameter->name = $child;

                continue;
            }

            switch ($child->id) {
                case self::T_AMP:
                    $parameter->isOutput = true;
                    break;

                case self::T_ELLIPSIS:
                    $parameter->isVariadic = true;
                    break;

                    // A variadic parameter is optional in itself, so a default marker
                    // beside one describes the same parameter in two different ways
                default:
                    if ($parameter->isVariadic) {
                        throw Exception\VariadicWithDefaultException::becauseVariadicHasDefault($offset);
                    }

                    $parameter->isOptional = true;
            }
        }

        return $parameter;
    }

    private static function reduceVariableLiteral(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\VariableLiteralNode(\substr($children->value, 1), $offset);
    }

    private function reduceTemplateArguments(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template arguments', $offset);
        }

        return new Type\Template\TemplateArgumentListNode($children, $offset);
    }

    private function reduceTemplateArgument(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $count = \count($children);
        $hint = null;

        // An "in T" or an "out T" argument puts a hint in front of the type
        if ($count === 2) {
            if ($this->features->hints === false) {
                throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template argument hints', $offset);
            }

            $hint = $children[0];
        }

        return new Type\Template\TemplateArgumentNode(
            $children[$count - 1],
            $hint,
            $offset,
        );
    }

    private static function reduceIdentifierWithExtraSpace(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(\rtrim($children->value), $offset);
    }

    private function reduceShapeFields(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $count = \count($children);

        // An empty shape carries no fields and needs no support for them
        if ($count === 0) {
            return [new Type\Shape\FieldsListNode(offset: $offset)];
        }

        if ($this->features->shapes === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('shape fields', $offset);
        }

        $parameters = null;

        // The "...<K, V>" suffix, in case of the shape is unsealed by a typed rest
        if ($children[$count - 1] instanceof Type\Template\TemplateArgumentListNode) {
            $parameters = $children[$count - 1];
            --$count;
        }

        if ($children[0] instanceof Type\Shape\FieldsListNode) {
            $fields = $children[0];
            // Whatever is left beside the fields is the "..." of an unsealed shape
            $unsealed = $count > 1;
        } else {
            $fields = new Type\Shape\FieldsListNode(offset: $offset);
            $unsealed = $count > 0;
        }

        if ($unsealed) {
            $fields->isSealed = false;
        }

        if ($parameters === null) {
            return [$fields];
        }

        return [$fields, $parameters];
    }

    private static function reduceShapeFieldsList(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $explicit = [];
        $implicit = false;

        foreach ($children as $field) {
            if ($field instanceof Type\Shape\ExplicitFieldNode) {
                $key = $field->getIndex();

                if (isset($explicit[$key])) {
                    throw Exception\ShapeFieldDuplicationException::becauseShapeFieldIsDuplicated($key, $field->offset);
                }

                $explicit[$key] = true;
            } else {
                $implicit = true;
            }
        }

        if ($explicit !== [] && $implicit) {
            throw Exception\ShapeKeysMixingException::becauseShapeKeysAreMixed($offset);
        }

        return new Type\Shape\FieldsListNode($children, offset: $offset);
    }

    private static function reduceExplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $count = \count($children);
        $name = $children[0];
        $value = $children[$count - 1];

        // In case of "nullable" suffix defined
        $optional = $count === 3;

        return match (true) {
            $name instanceof Type\Literal\IntLiteralNode
                => new Type\Shape\NumericFieldNode($name, $value, $optional, offset: $offset),
            $name instanceof Type\Literal\StringLiteralNode
                => new Type\Shape\StringNamedFieldNode($name, $value, $optional, offset: $offset),
            $name instanceof Type\ClassConstNode
                => new Type\Shape\ClassConstFieldNode($name, $value, $optional, offset: $offset),
            $name instanceof Type\ClassConstMaskNode
                => new Type\Shape\ClassConstMaskFieldNode($name, $value, $optional, offset: $offset),
            $name instanceof Type\ConstMaskNode
                => new Type\Shape\ConstMaskFieldNode($name, $value, $optional, offset: $offset),
            default => new Type\Shape\NamedFieldNode($name, $value, $optional, offset: $offset),
        };
    }

    private static function reduceShapeConstantKey(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $suffix = $children[1];

        switch (true) {
            // Some\Any::CONST and Some\Any::CONST_*
            case $suffix instanceof Type\Identifier:
                if (isset($children[2])) {
                    return new Type\ClassConstMaskNode($children[0], $suffix, $offset);
                }

                return new Type\ClassConstNode($children[0], $suffix, $offset);

                // Some\Any::*
            case $suffix === true:
                return new Type\ClassConstMaskNode($children[0], offset: $offset);

                // SOME_ANY_*
            default:
                return new Type\ConstMaskNode($children[0], $offset);
        }
    }

    private static function reduceImplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Shape\ImplicitFieldNode($children[0], offset: $offset);
    }

    private static function reduceTypeListOrOffsetSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return $children[0] ?? true;
    }
}
