<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.0.0
 */

declare(strict_types=1);

namespace TypeLang\Parser\Internal;

use TypeLang\Type;
use TypeLang\Parser\Exception;
use TypeLang\Parser\Internal;

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

/**
 * @template TResult of mixed = mixed
 *
 * @template-implements \Phplrt\Contracts\Parser\ParserInterface<TResult>
 */
abstract class CompilerExecutor implements \Phplrt\Contracts\Parser\ParserInterface
{
    /** @var int */
    public const T_WHITESPACE = 0;
    /** @var int */
    public const T_EQ = 1;
    /** @var int */
    public const T_NOT = 2;
    /** @var int */
    public const T_TRUE_LITERAL = 3;
    /** @var int */
    public const T_FALSE_LITERAL = 4;
    /** @var int */
    public const T_NULL_LITERAL = 5;
    /** @var int */
    public const T_NAME_WITH_SPACE = 6;
    /** @var int */
    public const T_NAME = 7;
    /** @var int */
    public const T_NS_DELIMITER = 8;
    /** @var int */
    public const T_OR = 9;
    /** @var int */
    public const T_COMMA = 10;
    /** @var int */
    public const T_DOUBLE_COLON = 11;
    /** @var int */
    public const T_COLON = 12;
    /** @var int */
    public const T_ANGLE_BRACKET_OPEN = 13;
    /** @var int */
    public const T_ANGLE_BRACKET_CLOSE = 14;
    /** @var int */
    public const T_QMARK = 15;
    /** @var int */
    public const T_BRACE_OPEN = 16;
    /** @var int */
    public const T_BRACE_CLOSE = 17;
    /** @var int */
    public const T_PARENTHESIS_OPEN = 18;
    /** @var int */
    public const T_PARENTHESIS_CLOSE = 19;
    /** @var int */
    public const T_SQUARE_BRACKET_OPEN = 20;
    /** @var int */
    public const T_SQUARE_BRACKET_CLOSE = 21;
    /** @var int */
    public const T_AMP = 22;
    /** @var int */
    public const T_ELLIPSIS = 23;
    /** @var int */
    public const T_ASSIGN = 24;
    /** @var int */
    public const T_ASTERISK = 25;
    /** @var int */
    public const T_THIS = 26;
    /** @var int */
    public const T_VARIABLE = 27;
    /** @var int */
    public const T_DQ_STRING_LITERAL = 28;
    /** @var int */
    public const T_SQ_STRING_LITERAL = 29;
    /** @var int */
    public const T_FLOAT_LITERAL = 30;
    /** @var int */
    public const T_BIN_INT_LITERAL = 31;
    /** @var int */
    public const T_OCT_INT_LITERAL = 32;
    /** @var int */
    public const T_HEX_INT_LITERAL = 33;
    /** @var int */
    public const T_DEC_INT_LITERAL = 34;
    /** @var int */
    public const T_COMMENT = 35;
    /** @var int */
    public const T_DOC_COMMENT = 36;

    /**
     * @var \Phplrt\Contracts\Parser\ParserInterface<TResult>
     */
    protected readonly \Phplrt\Contracts\Parser\ParserInterface $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:is(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:1))|(?:(?:not(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:2))|(?:(?:(?i:true)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:3))|(?:(?:(?i:false)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:4))|(?:(?:(?i:null)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:5))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+\\s++)(*MARK:6))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+)(*MARK:7))|(?:(?:\\\\)(*MARK:8))|(?:(?:\\|)(*MARK:9))|(?:(?:,)(*MARK:10))|(?:(?:::)(*MARK:11))|(?:(?::)(*MARK:12))|(?:(?:<)(*MARK:13))|(?:(?:>)(*MARK:14))|(?:(?:\\?)(*MARK:15))|(?:(?:\\{)(*MARK:16))|(?:(?:\\})(*MARK:17))|(?:(?:\\()(*MARK:18))|(?:(?:\\))(*MARK:19))|(?:(?:\\[)(*MARK:20))|(?:(?:\\])(*MARK:21))|(?:(?:&)(*MARK:22))|(?:(?:\\.\\.\\.)(*MARK:23))|(?:(?:=)(*MARK:24))|(?:(?:\\*)(*MARK:25))|(?:(?:\\$this(?!(?:[a-zA-Z0-9_\\x80-\\xff])))(*MARK:26))|(?:(?:\\$(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9_\\x80-\\xff])*+)(*MARK:27))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:28))|(?:(?:\'[^\'\\\\]*+(?:\\\\.[^\'\\\\]*+)*+\')(*MARK:29))|(?:(?:(?:[-+])?(?:(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+)\\.(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+))?|\\.(?:(?:[0-9])(?:_?(?:[0-9]))*+))(?:(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+)))?|(?:(?:[0-9])(?:_?(?:[0-9]))*+)(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+))))(*MARK:30))|(?:(?:(?:[-+])?0[bB](?:(?:[01])(?:_?(?:[01]))*+))(*MARK:31))|(?:(?:(?:[-+])?0(?:[oO](?:(?:[0-7])(?:_?(?:[0-7]))*+)|(?:_?(?:[0-7]))++))(*MARK:32))|(?:(?:(?:[-+])?0[xX](?:(?:[0-9a-fA-F])(?:_?(?:[0-9a-fA-F]))*+))(*MARK:33))|(?:(?:(?:[-+])?(?:(?:(?:[1-9])(?:_?(?:[0-9]))*+)|0))(*MARK:34))|(?:(?:(?:\\/\\/|\\#)[^\\r\\n]*+)(*MARK:35))|(?:(?:\\/\\*.*?\\*\\/)(*MARK:36))|(?:(?:[^\\s]++)(*MARK:37)))/Ssm',
            channels: [
                'Hidden',
                35 => 'Hidden',
                'Hidden',
                'Unknown',
            ],
            names: [
                'T_WHITESPACE',
                'T_EQ',
                'T_NOT',
                'T_TRUE_LITERAL',
                'T_FALSE_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_FLOAT_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Alternation([1, 141]),
                new \Phplrt\Parser\Grammar\Concatenation([2, 136]),
                new \Phplrt\Parser\Grammar\Concatenation([3, 133]),
                new \Phplrt\Parser\Grammar\Concatenation([4, 130]),
                new \Phplrt\Parser\Grammar\Alternation([5, 7]),
                new \Phplrt\Parser\Grammar\Concatenation([6, 7]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, false),
                new \Phplrt\Parser\Grammar\Concatenation([8, 125]),
                new \Phplrt\Parser\Grammar\Alternation([9, 12, 13, 27]),
                new \Phplrt\Parser\Grammar\Concatenation([10, 0, 11]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Alternation([14, 26]),
                new \Phplrt\Parser\Grammar\Alternation([15, 18, 19, 24, 25]),
                new \Phplrt\Parser\Grammar\Alternation([16, 17]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FLOAT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Alternation([20, 21, 22, 23]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BIN_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OCT_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_HEX_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DEC_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Concatenation([28, 54]),
                new \Phplrt\Parser\Grammar\Alternation([29, 52]),
                new \Phplrt\Parser\Grammar\Concatenation([30, 44]),
                new \Phplrt\Parser\Grammar\Alternation([31, 43]),
                new \Phplrt\Parser\Grammar\Concatenation([32, 33, 41]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NS_DELIMITER, false),
                new \Phplrt\Parser\Grammar\Alternation([34, 35, 36, 37, 38, 39, 40]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EQ, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NOT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Repetition(42, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([32, 33]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 41]),
                new \Phplrt\Parser\Grammar\Optional(45),
                new \Phplrt\Parser\Grammar\Alternation([46, 51]),
                new \Phplrt\Parser\Grammar\Concatenation([47, 48, 50]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Repetition(49, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([33, 47]),
                new \Phplrt\Parser\Grammar\Optional(33),
                new \Phplrt\Parser\Grammar\Concatenation([32, 46]),
                new \Phplrt\Parser\Grammar\Concatenation([47, 33, 53]),
                new \Phplrt\Parser\Grammar\Optional(46),
                new \Phplrt\Parser\Grammar\Optional(55),
                new \Phplrt\Parser\Grammar\Alternation([56, 60, 81, 92, 102]),
                new \Phplrt\Parser\Grammar\Concatenation([57, 58]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, true),
                new \Phplrt\Parser\Grammar\Alternation([59, 46]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 53]),
                new \Phplrt\Parser\Grammar\Concatenation([10, 61, 11, 78]),
                new \Phplrt\Parser\Grammar\Optional(62),
                new \Phplrt\Parser\Grammar\Concatenation([63, 74, 77]),
                new \Phplrt\Parser\Grammar\Concatenation([0, 64, 66, 68, 72]),
                new \Phplrt\Parser\Grammar\Optional(65),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, true),
                new \Phplrt\Parser\Grammar\Optional(67),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ELLIPSIS, true),
                new \Phplrt\Parser\Grammar\Optional(69),
                new \Phplrt\Parser\Grammar\Alternation([70, 71]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_VARIABLE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Optional(73),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, true),
                new \Phplrt\Parser\Grammar\Repetition(75, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([76, 63]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Optional(76),
                new \Phplrt\Parser\Grammar\Optional(79),
                new \Phplrt\Parser\Grammar\Concatenation([80, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([82, 91]),
                new \Phplrt\Parser\Grammar\Concatenation([83, 84, 88, 77, 90]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([85, 87]),
                new \Phplrt\Parser\Grammar\Concatenation([86, 87]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Alternation([47, 0]),
                new \Phplrt\Parser\Grammar\Repetition(89, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([76, 84]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Predicate(10, false),
                new \Phplrt\Parser\Grammar\Concatenation([93, 60]),
                new \Phplrt\Parser\Grammar\Concatenation([83, 94, 100, 77, 90]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 95]),
                new \Phplrt\Parser\Grammar\Repetition(96, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([97, 98]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 0]),
                new \Phplrt\Parser\Grammar\Concatenation([99, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, false),
                new \Phplrt\Parser\Grammar\Repetition(101, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([76, 94]),
                new \Phplrt\Parser\Grammar\Concatenation([103, 104, 77, 124]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([105, 123]),
                new \Phplrt\Parser\Grammar\Concatenation([106, 119]),
                new \Phplrt\Parser\Grammar\Concatenation([107, 117]),
                new \Phplrt\Parser\Grammar\Alternation([108, 116]),
                new \Phplrt\Parser\Grammar\Concatenation([109, 114, 80, 0]),
                new \Phplrt\Parser\Grammar\Alternation([110, 8]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 111]),
                new \Phplrt\Parser\Grammar\Predicate(112, true),
                new \Phplrt\Parser\Grammar\Concatenation([113, 80]),
                new \Phplrt\Parser\Grammar\Optional(6),
                new \Phplrt\Parser\Grammar\Optional(115),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, true),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Repetition(118, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([76, 107]),
                new \Phplrt\Parser\Grammar\Optional(120),
                new \Phplrt\Parser\Grammar\Concatenation([76, 121]),
                new \Phplrt\Parser\Grammar\Concatenation([67, 122]),
                new \Phplrt\Parser\Grammar\Optional(82),
                new \Phplrt\Parser\Grammar\Optional(121),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(126, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([127, 128, 129]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Optional(0),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(131, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([132, 4]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, false),
                new \Phplrt\Parser\Grammar\Repetition(134, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([135, 3]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Optional(137),
                new \Phplrt\Parser\Grammar\Concatenation([138, 140, 6, 0, 80, 0]),
                new \Phplrt\Parser\Grammar\Concatenation([36, 139]),
                new \Phplrt\Parser\Grammar\Optional(37),
                new \Phplrt\Parser\Grammar\Alternation([0, 69]),
                new \Phplrt\Parser\Grammar\Concatenation([69, 137]),
            ],
            initial: 0,
            reducers: [
                0 => $this->reduceType(...),
                2 => $this->reduceUnionType(...),
                3 => $this->reduceIntersectionType(...),
                5 => self::reduceNullableType(...),
                7 => $this->reduceListOrOffsetType(...),
                12 => self::reduceThisType(...),
                13 => $this->reduceLiteralType(...),
                16 => self::reduceDoubleQuotedStringLiteralType(...),
                17 => self::reduceSingleQuotedStringLiteralType(...),
                18 => self::reduceFloatLiteralType(...),
                19 => self::reduceIntLiteralType(...),
                24 => self::reduceTrueLiteralType(...),
                25 => self::reduceFalseLiteralType(...),
                26 => self::reduceNullLiteralType(...),
                27 => $this->reduceNamedType(...),
                28 => self::reduceNameOrMask(...),
                31 => self::reduceFullQualifiedName(...),
                33 => self::reduceIdentifier(...),
                43 => self::reduceRelativeName(...),
                47 => self::reduceWildcardType(...),
                51 => self::reduceNamespacedMask(...),
                61 => self::reduceCallableParameters(...),
                63 => self::reduceCallableParameter(...),
                69 => self::reduceVariable(...),
                82 => $this->reduceTemplateArguments(...),
                84 => $this->reduceTemplateArgument(...),
                86 => self::reduceIdentifierWithExtraSpace(...),
                93 => $this->reduceTemplateParameters(...),
                94 => self::reduceTemplateParameter(...),
                97 => self::reduceTemplateBoundEdge(...),
                102 => $this->reduceShapeFields(...),
                106 => self::reduceShapeFieldsList(...),
                108 => self::reduceExplicitField(...),
                116 => self::reduceImplicitField(...),
                126 => self::reduceListOrOffsetSuffix(...),
                138 => self::reduceTernaryExpressionOperator(...),
            ],
            lookahead: [
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    15 => true,
                ],
                [
                    15 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                ],
                [
                    18 => true,
                ],
                [
                    19 => true,
                ],
                [
                    26 => true,
                ],
                [
                    3 => true,
                    true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    3 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    28 => true,
                    true,
                ],
                [
                    28 => true,
                ],
                [
                    29 => true,
                ],
                [
                    30 => true,
                ],
                [
                    31 => true,
                    true,
                    true,
                    true,
                ],
                [
                    31 => true,
                ],
                [
                    32 => true,
                ],
                [
                    33 => true,
                ],
                [
                    34 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    5 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    7 => true,
                ],
                [
                    6 => true,
                ],
                [
                    1 => true,
                ],
                [
                    2 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    5 => true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    8 => true,
                    25 => true,
                ],
                [
                    25 => true,
                ],
                [
                    25 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    25 => true,
                ],
                null,
                null,
                [
                    11 => true,
                    13 => true,
                    16 => true,
                    18 => true,
                ],
                [
                    11 => true,
                ],
                [
                    11 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    25 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    22 => true,
                ],
                null,
                [
                    23 => true,
                ],
                null,
                [
                    26 => true,
                    true,
                ],
                [
                    27 => true,
                ],
                [
                    26 => true,
                ],
                null,
                [
                    24 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    10 => true,
                ],
                null,
                null,
                [
                    12 => true,
                ],
                [
                    12 => true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    6 => true,
                ],
                [
                    6 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    14 => true,
                ],
                null,
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    24 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    24 => true,
                ],
                [
                    24 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    16 => true,
                ],
                [
                    16 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    18 => true,
                    25 => true,
                    true,
                    28 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    12 => true,
                    15 => true,
                ],
                null,
                null,
                [
                    15 => true,
                ],
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    10 => true,
                ],
                null,
                [
                    10 => true,
                ],
                [
                    23 => true,
                ],
                null,
                null,
                [
                    17 => true,
                ],
                null,
                [
                    20 => true,
                ],
                [
                    20 => true,
                ],
                null,
                [
                    21 => true,
                ],
                null,
                [
                    22 => true,
                ],
                [
                    22 => true,
                ],
                null,
                [
                    9 => true,
                ],
                [
                    9 => true,
                ],
                null,
                [
                    1 => true,
                ],
                [
                    1 => true,
                ],
                null,
                [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    15 => true,
                    18 => true,
                    25 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    26 => true,
                    true,
                ],
            ],
            kept: [
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
            ],
            choicePrediction: [
                [
                    1 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    15 => [
                        1,
                    ],
                    18 => [
                        1,
                    ],
                    25 => [
                        1,
                    ],
                    28 => [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    [
                        1,
                    ],
                    27 => [
                        141,
                    ],
                ],
                4 => [
                    15 => [
                        5,
                    ],
                    1 => [
                        7,
                    ],
                    2 => [
                        7,
                    ],
                    3 => [
                        7,
                    ],
                    4 => [
                        7,
                    ],
                    5 => [
                        7,
                    ],
                    6 => [
                        7,
                    ],
                    7 => [
                        7,
                    ],
                    8 => [
                        7,
                    ],
                    18 => [
                        7,
                    ],
                    25 => [
                        7,
                    ],
                    [
                        7,
                    ],
                    28 => [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                    [
                        7,
                    ],
                ],
                8 => [
                    18 => [
                        9,
                    ],
                    26 => [
                        12,
                    ],
                    3 => [
                        13,
                        27,
                    ],
                    4 => [
                        13,
                        27,
                    ],
                    5 => [
                        13,
                        27,
                    ],
                    28 => [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    [
                        13,
                    ],
                    1 => [
                        27,
                    ],
                    2 => [
                        27,
                    ],
                    6 => [
                        27,
                    ],
                    7 => [
                        27,
                    ],
                    8 => [
                        27,
                    ],
                    25 => [
                        27,
                    ],
                ],
                13 => [
                    3 => [
                        14,
                    ],
                    [
                        14,
                    ],
                    28 => [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    [
                        14,
                    ],
                    5 => [
                        26,
                    ],
                ],
                [
                    28 => [
                        15,
                    ],
                    [
                        15,
                    ],
                    [
                        18,
                    ],
                    [
                        19,
                    ],
                    [
                        19,
                    ],
                    [
                        19,
                    ],
                    [
                        19,
                    ],
                    3 => [
                        24,
                    ],
                    4 => [
                        25,
                    ],
                ],
                [
                    28 => [
                        16,
                    ],
                    [
                        17,
                    ],
                ],
                19 => [
                    31 => [
                        20,
                    ],
                    [
                        21,
                    ],
                    [
                        22,
                    ],
                    [
                        23,
                    ],
                ],
                28 => [
                    1 => [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    [
                        29,
                    ],
                    25 => [
                        52,
                    ],
                ],
                30 => [
                    8 => [
                        31,
                    ],
                    1 => [
                        43,
                    ],
                    2 => [
                        43,
                    ],
                    3 => [
                        43,
                    ],
                    4 => [
                        43,
                    ],
                    5 => [
                        43,
                    ],
                    6 => [
                        43,
                    ],
                    7 => [
                        43,
                    ],
                ],
                33 => [
                    7 => [
                        34,
                    ],
                    6 => [
                        35,
                    ],
                    1 => [
                        36,
                    ],
                    2 => [
                        37,
                    ],
                    3 => [
                        38,
                    ],
                    4 => [
                        39,
                    ],
                    5 => [
                        40,
                    ],
                ],
                45 => [
                    25 => [
                        46,
                    ],
                    8 => [
                        51,
                    ],
                ],
                55 => [
                    11 => [
                        56,
                    ],
                    18 => [
                        60,
                    ],
                    13 => [
                        81,
                        92,
                    ],
                    16 => [
                        102,
                    ],
                ],
                58 => [
                    1 => [
                        59,
                    ],
                    [
                        59,
                    ],
                    [
                        59,
                    ],
                    [
                        59,
                    ],
                    [
                        59,
                    ],
                    [
                        59,
                    ],
                    [
                        59,
                    ],
                    25 => [
                        46,
                    ],
                ],
                69 => [
                    27 => [
                        70,
                    ],
                    26 => [
                        71,
                    ],
                ],
                84 => [
                    1 => [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    7 => [
                        87,
                    ],
                    [
                        87,
                    ],
                    15 => [
                        87,
                    ],
                    18 => [
                        87,
                    ],
                    25 => [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                    [
                        87,
                    ],
                ],
                87 => [
                    1 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    15 => [
                        0,
                    ],
                    18 => [
                        0,
                    ],
                    26 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                ],
                96 => [
                    1 => [
                        97,
                    ],
                    [
                        97,
                    ],
                    [
                        97,
                    ],
                    [
                        97,
                    ],
                    [
                        97,
                    ],
                    [
                        97,
                    ],
                    [
                        97,
                    ],
                    24 => [
                        98,
                    ],
                ],
                107 => [
                    15 => [
                        116,
                    ],
                    27 => [
                        116,
                    ],
                ],
                109 => [
                    8 => [
                        8,
                    ],
                    18 => [
                        8,
                    ],
                    25 => [
                        8,
                    ],
                    [
                        8,
                    ],
                    28 => [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                    [
                        8,
                    ],
                ],
                140 => [
                    1 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    15 => [
                        0,
                    ],
                    18 => [
                        0,
                    ],
                    25 => [
                        0,
                    ],
                    28 => [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                    [
                        0,
                    ],
                ],
            ],
            expectations: [
                'T_WHITESPACE',
                'T_EQ',
                'T_NOT',
                'T_TRUE_LITERAL',
                'T_FALSE_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_FLOAT_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
                '/[^\\s]++/',
            ],
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    private function reduceType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->conditions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('conditional expressions', $offset);
        }

        $condition = $children[1]
            ? new Type\Condition\NotEqualConditionNode($children[0], $children[2], $offset)
            : new Type\Condition\EqualConditionNode($children[0], $children[2], $offset);

        return new Type\TernaryExpressionNode(
            $condition,
            $children[3],
            $children[4],
            $offset,
        );
    }

    private function reduceUnionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->unions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('union types', $offset);
        }

        $statement = new Type\UnionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private function reduceIntersectionType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        if ($this->features->intersections === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('intersection types', $offset);
        }

        $statement = new Type\IntersectionTypeNode($children);
        $statement->offset = $offset;

        return $statement;
    }

    private static function reduceNullableType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\NullableTypeNode($children[0], $offset);
    }

    private function reduceListOrOffsetType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $statement = $children[0];
        $count = \count($children);

        for ($i = 1; $i < $count; ++$i) {
            $child = $children[$i];

            switch (true) {
                case $child === true:
                    if ($this->features->lists === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('square bracket list types', $offset);
                    }

                    $statement = new Type\TypesListNode($statement, $offset);
                    break;
                case $child instanceof Type\TypeNode:
                    if ($this->features->offsets === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('type offsets', $offset);
                    }

                    $statement = new Type\TypeOffsetAccessNode($statement, $child, $offset);
                    break;
                default:
                    throw Exception\InternalSemanticException::becauseSubNodeIsUnexpected(
                        \get_debug_type($child),
                        $offset,
                    );
            }
        }

        return $statement;
    }

    private static function reduceThisType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\ThisNode($offset);
    }

    private function reduceLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if ($this->features->literals === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('literal values', $offset);
        }
        return $children;
    }

    private static function reduceDoubleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            Internal\StringDecoder::unpackAndDecode($children->value, true),
            $children->value,
            $offset,
        );
    }

    private static function reduceSingleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            Internal\StringDecoder::unpackAndDecode($children->value, false),
            $children->value,
            $offset,
        );
    }

    private static function reduceFloatLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\FloatLiteralNode(
            Internal\FloatDecoder::decode($children->value),
            $children->value,
            $offset,
        );
    }

    private static function reduceIntLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $decoded = Internal\IntDecoder::decode($children->value);

        return new Type\Literal\IntLiteralNode(
            $decoded->value,
            $children->value,
            $decoded->decimal,
            $offset,
        );
    }

    private static function reduceTrueLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(true, $children->value, $offset);
    }

    private static function reduceFalseLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(false, $children->value, $offset);
    }

    private static function reduceNullLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\NullLiteralNode(
            $children->value,
            $offset,
        );
    }

    private function reduceNamedType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $head = $children[0];
        $suffix = $children[1] ?? null;

        if ($head instanceof Type\ConstMaskNode) {
            if ($suffix !== null) {
                throw Exception\ConstMaskException::becauseNothingFollowsAMask($offset);
            }

            return $head;
        }

        switch (true) {
            // Some\Any
            case $suffix === null:
                return new Type\NamedTypeNode($children[0], null, null, $offset);

            // Some\Any<T, U>
            case $suffix instanceof Type\Template\TemplateArgumentListNode:
                return new Type\NamedTypeNode($children[0], $suffix, null, $offset);

            // Some\Any{name: T, ...<K, V>}
            case $suffix instanceof Type\Shape\FieldsListNode:
                return new Type\NamedTypeNode($children[0], $children[2] ?? null, $suffix, $offset);

            // Some\Any(T, U): V
            case $suffix instanceof Type\Callable\CallableParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $offset);
                }

                return new Type\CallableTypeNode($children[0], $suffix, $children[2] ?? null, null, $offset);

            // Some\Any<T, U>(T): U
            case $suffix instanceof Type\Template\TemplateParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $offset);
                }

                return new Type\CallableTypeNode($children[0], $children[2], $children[3] ?? null, $suffix, $offset);

            // Some\Any::CONST, Some\Any::CONST_* and Some\Any::*
            default:
                if (\count($children) === 3 && $children[2] instanceof Type\Identifier) {
                    return new Type\ClassConstNode($children[0], $children[2], $offset);
                }

                return new Type\ClassConstMaskNode(
                    $children[0],
                    new Type\MaskNode(\array_slice($children, 2), $children[2]->offset),
                    $offset,
                );
        }
    }

    private static function reduceNameOrMask(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $head = $children[0];

        // "*_SOME"
        if (!$head instanceof Type\Name) {
            return new Type\ConstMaskNode(new Type\MaskNode($children, $offset), false, $offset);
        }

        // "Some\Any"
        if (!isset($children[1])) {
            return $head;
        }

        $parts = $head->parts;

        if ($children[1] instanceof Type\MaskNode) {
            // "Some\Any\*"
            $mask = $children[1];
        } else {
            // "Some\Any\SOME_*"
            $segment = \array_pop($parts);
            $mask = new Type\MaskNode([$segment, ...\array_slice($children, 1)], $segment->offset);
        }

        return new Type\ConstMaskNode(
            $mask,
            $parts === []
                ? $head->isFullyQualified
                : new Type\Name($parts, $head->isFullyQualified, $head->offset),
            $offset,
        );
    }

    private static function reduceFullQualifiedName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, true, $offset);
    }

    private static function reduceIdentifier(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(
            $children->id === self::T_NAME_WITH_SPACE
                ? \rtrim($children->value)
                : $children->value,
            $offset,
        );
    }

    private static function reduceRelativeName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Name($children, false, $offset);
    }

    private static function reduceWildcardType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\WildcardNode($offset);
    }

    private static function reduceNamespacedMask(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\MaskNode($children, $offset);
    }

    private static function reduceCallableParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Callable\CallableParameterListNode($children, $offset);
    }

    private static function reduceCallableParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $parameter = new Type\Callable\CallableParameterNode(
            $children[0],
            null,
            false,
            false,
            false,
            $offset,
        );

        for ($i = 1, $count = \count($children); $i < $count; ++$i) {
            $child = $children[$i];

            if ($child instanceof Type\VariableNode) {
                $parameter->name = $child;

                continue;
            }

            switch ($child->id) {
                case self::T_AMP:
                    $parameter->isOutput = true;
                    break;

                case self::T_ELLIPSIS:
                    $parameter->isVariadic = true;
                    break;

                default:
                    if ($parameter->isVariadic) {
                        throw Exception\VariadicWithDefaultException::becauseVariadicHasDefault($offset);
                    }

                    $parameter->isOptional = true;
            }
        }

        return $parameter;
    }

    private static function reduceVariable(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\VariableNode(
            new Type\Identifier(\substr($children->value, 1), $offset),
            $offset,
        );
    }

    private function reduceTemplateArguments(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template arguments', $offset);
        }

        return new Type\Template\TemplateArgumentListNode($children, $offset);
    }

    private function reduceTemplateArgument(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if (\is_array($children)) {
            if ($this->features->hints === false) {
                throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template argument hints', $offset);
            }

            return new Type\Template\TemplateArgumentNode($children[1], $children[0], $offset);
        }

        return new Type\Template\TemplateArgumentNode($children, null, $offset);
    }

    private static function reduceIdentifierWithExtraSpace(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(\rtrim($children->value), $offset);
    }

    private function reduceTemplateParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template parameters', $offset);
        }

        return new Type\Template\TemplateParameterListNode($children, $offset);
    }

    private static function reduceTemplateParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $upper = $lower = $default = null;

        foreach (\array_slice($children, 1) as $limit) {
            if (!$limit instanceof Type\Template\TemplateBoundEdgeNode) {
                if ($default !== null) {
                    throw Exception\TemplateBoundException::becauseBoundIsDuplicated('default', $limit->offset);
                }

                $default = $limit;

                continue;
            }

            if ($default !== null) {
                throw Exception\TemplateBoundException::becauseDefaultIsNotWrittenLast($limit->operator->offset);
            }

            switch ($limit->operator->value) {
                case 'of':
                case 'as':
                    if ($upper !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('upper bound', $limit->offset);
                    }

                    $upper = $limit;
                    break;

                case 'super':
                    if ($lower !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('lower bound', $limit->offset);
                    }

                    $lower = $limit;
                    break;

                default:
                    throw Exception\TemplateBoundException::becauseOperatorIsUnknown(
                        $limit->operator->value,
                        $limit->operator->offset,
                    );
            }
        }

        return new Type\Template\TemplateParameterNode($children[0], $upper, $lower, $default, $offset);
    }

    private static function reduceTemplateBoundEdge(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Template\TemplateBoundEdgeNode($children[0], $children[1], $offset);
    }

    private function reduceShapeFields(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $count = \count($children);

        if ($count === 0) {
            return [new Type\Shape\FieldsListNode([], true, $offset)];
        }

        if ($this->features->shapes === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('shape fields', $offset);
        }

        $parameters = null;

        // The "...<K, V>" suffix
        if ($children[$count - 1] instanceof Type\Template\TemplateArgumentListNode) {
            $parameters = $children[$count - 1];
            --$count;
        }

        if ($children[0] instanceof Type\Shape\FieldsListNode) {
            $fields = $children[0];
            $unsealed = $count > 1;
        } else {
            $fields = new Type\Shape\FieldsListNode([], true, $offset);
            $unsealed = $count > 0;
        }

        if ($unsealed) {
            $fields->isSealed = false;
        }

        if ($parameters === null) {
            return [$fields];
        }

        return [$fields, $parameters];
    }

    private static function reduceShapeFieldsList(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $explicit = false;
        $implicit = false;
        $indexed = [];

        foreach ($children as $field) {
            if (!$field instanceof Type\Shape\ExplicitFieldNode) {
                $implicit = true;

                continue;
            }

            $explicit = true;

            if (!$field instanceof Type\Shape\SimpleFieldNodeInterface) {
                continue;
            }

            $key = $field->getIndex();

            if (isset($indexed[$key])) {
                throw Exception\ShapeFieldDuplicationException::becauseShapeFieldIsDuplicated($key, $field->offset);
            }

            $indexed[$key] = true;
        }

        if ($explicit && $implicit) {
            throw Exception\ShapeKeysMixingException::becauseShapeKeysAreMixed($offset);
        }

        return new Type\Shape\FieldsListNode($children, true, $offset);
    }

    private static function reduceExplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $count = \count($children);
        $name = $children[0];
        $value = $children[$count - 1];

        $optional = $count === 3;

        return match (true) {
            // "a", "true" and "null"
            $name instanceof Type\Identifier
                => new Type\Shape\NamedFieldNode($name, $value, $optional, $offset),
            $name instanceof Type\Literal\IntLiteralNode,
            $name instanceof Type\Literal\StringLiteralNode
                => new Type\Shape\ScalarFieldNode($name, $value, $optional, $offset),
            // "Some::CONST", "Some::CONST_*" and "JSON_*"
            $name instanceof Type\ClassConstNode,
            $name instanceof Type\ClassConstMaskNode,
            $name instanceof Type\ConstMaskNode
                => new Type\Shape\ComplexFieldNode($name, $value, $optional, $offset),
            default => throw Exception\ShapeKeyException::becauseKeyIsNotAName($name->offset),
        };
    }

    private static function reduceImplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Shape\ImplicitFieldNode($children[0], false, $offset);
    }

    private static function reduceListOrOffsetSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return $children[0] ?? true;
    }

    private static function reduceTernaryExpressionOperator(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \count($children) === 2;
    }
}
